python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/164218354
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/161990146
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/159899860
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/164472841
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/163170515
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/162014176
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/162374998
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/160322710
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/159904067
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/158444351
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/157009885
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/159235158
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/160322340
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/126667937
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/126071702
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/126071693
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/129676357
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/126071752
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/129438667
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/126667908
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/126071758
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/127741769
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/129698738
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/135460580
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/135460616
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/129676403
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/139873189
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/139873263
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/160322492
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/158701963
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/158129234
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/157893488
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/157470498
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/156387903
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/153130967
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/153958718
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/153434949
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/156053028
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/152613021
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/153238290
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/151833621
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/153392148
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/151162618
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/152612859
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/152708616
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/155124342
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/152622267
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/151122617
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/153515456
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/153515430
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/150852372
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/150745842
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/149336887
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/150140816
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/148716748
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/148751482
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/147049830
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/146179005
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/145316659
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/145223425
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/142085936
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/143446941
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/134788273
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/140630190
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/137560944
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/134695507
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/133034022
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/128060151
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/128953992
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/141517953
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/125751188
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/142932818
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/138647368
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/131051352
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/134148936
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/136202257
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/135595553
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/134774335
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/133539167
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/133050373
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/133050428
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/127741742
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/128158539
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/128158666
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/128281043
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/128280958
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/128158673
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/128158598
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/129783475
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/134632539
python3 redsea.py --preset default --skip --account tv5 --bruteforce https://listen.tidal.com/album/131155011
